import 'package:flutter/material.dart';
import '../models/project_model.dart';

final List<Project> projects = [
  Project(
    title: 'Personal Portfolio',
    description:
        'The interactive, professional showcase you are viewing right now.',
    logoPath: 'assets/portfolio/logo.png',
    splashPath: 'assets/reisty/splash.png',
    screenshotPaths: [],
    baseColor: const Color(0xFF50C878),
    technologies: ['Flutter', 'Flutter Animate', 'Agentic AI'],
    features: [
      'Dynamic Theming',
      'Interactive 3D Cards',
      'AI-Accelerated Workflow',
    ],
    role: 'Lead Architect',
    isAiAccelerated: true,
  ),
  Project(
    title: 'Textura',
    description: 'A Flutter package that wraps widgets in beautiful textures.',
    logoPath: 'assets/projects/textura.png',
    splashPath: 'assets/projects/textura.png',
    screenshotPaths: [
      'assets/projects/textura1.png',
      'assets/projects/textura2.png',
      'assets/projects/textura3.png',
    ],
    baseColor: const Color(0xFF4CAF50),
    technologies: ['Flutter', 'Dart', 'Custom Painters'],
    features: ['Modular textures', 'Cozy widget wrappers', 'High performance'],
    role: 'Open Source Contributor',
    isOpenSource: true,
    url: 'https://github.com/Yczar/textura',
  ),
  Project(
    title: 'Celest',
    description: 'The premier Flutter cloud platform for backend-less apps.',
    logoPath: 'assets/projects/celest.png',
    splashPath: 'assets/projects/celest.png',
    screenshotPaths: [],
    baseColor: const Color(0xFF2196F3),
    technologies: ['Flutter', 'Dart', 'Cloud Infrastructure'],
    features: ['Cloud functions', 'Seamless integration', 'Developer tools'],
    role: 'Open Source Contributor',
    isOpenSource: true,
    url: 'https://github.com/celest-dev/celest',
  ),
  Project(
    title: 'Leisure Trove',
    description: 'A social app for travellers, tourists and locals.',
    logoPath: 'assets/leisure_trove/logo.png',
    splashPath: 'assets/leisure_trove/splash.png',
    screenshotPaths: [
      'assets/leisure_trove/image1.png',
      'assets/leisure_trove/image2.png',
      'assets/leisure_trove/image3.png',
    ],
    baseColor: const Color(0xFF2196F3),
    technologies: ['Flutter', 'Firebase Auth', 'Cloud Firestore', 'Stripe'],
    features: [
      'Local guides integration',
      'Itinerary planner',
      'Social moments',
    ],
    role: 'Lead Developer',
  ),
  Project(
    title: 'Breakout Revival',
    description:
        'A modern, high-performance revival of the classic arcade game.',
    logoPath: 'assets/projects/breakout.png',
    splashPath: 'assets/projects/breakout.png',
    screenshotPaths: [
      'assets/projects/breakout1.png',
      'assets/projects/breakout2.png',
      'assets/projects/breakout3.png',
      'assets/projects/breakout4.png',
    ],
    baseColor: const Color(0xFFE91E63),
    technologies: ['Flutter', 'Flame Engine', 'Dart'],
    features: ['Retro visuals', 'Physics-based gameplay', 'Level editor'],
    role: 'Open Source Contributor',
    isOpenSource: true,
    url: 'https://github.com/hngx-org/Team-Newton-breakout-Revival',
  ),

  Project(
    title: 'Reisty',
    description: 'A mobile app with real-time features for foodies.',
    logoPath: 'assets/reisty/logo.png',
    splashPath: 'assets/reisty/splash.png',
    screenshotPaths: [
      'assets/reisty/image1.png',
      'assets/reisty/image2.png',
      'assets/reisty/image3.png',
    ],
    baseColor: const Color(0xFFE91E63),
    technologies: ['Flutter', 'Firebase', 'Google Maps API', 'Node.js'],
    features: ['Real-time order tracking', 'Smart discovery', 'Social reviews'],
    role: 'Full Stack Flutter Developer',
  ),
  Project(
    title: 'Re:Chops',
    description: 'A restaurant reservation app with rich features.',
    logoPath: 'assets/chops/logo.png',
    splashPath: 'assets/chops/splash.png',
    screenshotPaths: [
      'assets/chops/image1.png',
      'assets/chops/image2.png',
      'assets/chops/image3.png',
    ],
    baseColor: const Color(0xFF4CAF50),
    technologies: ['Flutter', 'AWS', 'PostgreSQL', 'Redux'],
    features: ['Instant table booking', 'Curated menus', 'Loyalty rewards'],
    role: 'Mobile Architect',
  ),

  Project(
    title: 'Routinger',
    description: 'Smart task scheduler designed for route optimization.',
    logoPath: 'assets/projects/routinger.png',
    splashPath: 'assets/projects/routinger.png',
    screenshotPaths: [],
    baseColor: const Color(0xFF009688),
    technologies: ['Flutter', 'Dart', 'Pathfinding Algorithms'],
    features: ['Route optimization', 'Task scheduling', 'Offline support'],
    role: 'Open Source Contributor',
    isOpenSource: true,
    url: 'https://github.com/theexidge/routinger',
  ),
  Project(
    title: 'Errand Buddies',
    description: 'An e-commerce platform for goods and services.',
    logoPath: 'assets/errand_buddies/logo.png',
    splashPath: 'assets/errand_buddies/splash.png',
    screenshotPaths: [
      'assets/errand_buddies/image1.png',
      'assets/errand_buddies/image2.png',
      'assets/errand_buddies/image3.png',
    ],
    baseColor: const Color(0xFFFF9800),
    technologies: ['Flutter', 'MongoDB', 'Express', 'JWT'],
    features: [
      'Secure marketplace',
      'Peer-to-peer messaging',
      'Service bidding',
    ],
    role: 'Frontend Developer',
    isAiAccelerated: true,
  ),
  Project(
    title: 'Errand Vendors',
    description: 'Vendor app for order management and analysis.',
    logoPath: 'assets/errand_vendors/logo.png',
    splashPath: 'assets/errand_vendors/splash.png',
    screenshotPaths: [
      'assets/errand_vendors/image1.png',
      'assets/errand_vendors/image2.png',
      'assets/errand_vendors/image3.png',
    ],
    baseColor: const Color(0xFF9C27B0),
    technologies: ['Flutter', 'Chart.js integration', 'Firebase Messaging'],
    features: ['Advanced analytics', 'Inventory control', 'Order workflow'],
    role: 'Full Stack Engineer',
    isAiAccelerated: true,
  ),
  Project(
    title: 'Speed Reader',
    description: 'A PDF reader app with reading speed enhancements.',
    logoPath: 'assets/speed_reader/logo.png',
    splashPath: 'assets/speed_reader/splash.png',
    screenshotPaths: [
      'assets/speed_reader/image1.png',
      'assets/speed_reader/image2.png',
      'assets/speed_reader/image3.png',
    ],
    baseColor: const Color(0xFF607D8B),
    technologies: ['Flutter', 'PDF.js', 'Hive', 'Natural Language Processing'],
    features: ['Bionic reading mode', 'OCR support', 'Sync across devices'],
    role: 'Primary Developer',
    isAiAccelerated: true,
  ),
  Project(
    title: 'Riddlesworld',
    description: 'An immersive puzzle platform with intellectual challenges.',
    logoPath: 'assets/projects/riddlesworld.png',
    splashPath: 'assets/projects/riddlesworld.png',
    screenshotPaths: [
      'assets/projects/riddlesworld1.png',
      'assets/projects/riddlesworld2.png',
      'assets/projects/riddlesworld3.png',
      'assets/projects/riddlesworld4.png',
    ],
    baseColor: const Color(0xFFFF9800),
    technologies: ['Flutter', 'Dart', 'JSON DB'],
    features: [
      'Interactive riddles',
      'Global leaderboards',
      'Puzzle world-building',
    ],
    role: 'Open Source Contributor',
    isOpenSource: true,
    url: 'https://github.com/clubgamma/RiddlesWorld',
  ),
];
