import 'package:flutter/material.dart';
import '../models/project_model.dart';

final List<Project> projects = [
  Project(
    title: 'Personal Portfolio',
    description:
        'The interactive, professional showcase you are viewing right now.',
    logoPath: 'assets/portfolio/logo.png',
    splashPath: 'assets/reisty/splash.png',
    screenshotPaths: [],
    baseColor: const Color(0xFF50C878),
    technologies: ['Flutter', 'Flutter Animate', 'Agentic AI'],
    features: [
      'Dynamic Theming',
      'Interactive 3D Cards',
      'AI-Accelerated Workflow',
    ],
    role: 'Lead Architect',
    isAiAccelerated: true,
  ),
  Project(
    title: 'Reisty',
    description: 'A mobile app with real-time features for foodies.',
    logoPath: 'assets/reisty/logo.png',
    splashPath: 'assets/reisty/splash.png',
    screenshotPaths: [
      'assets/reisty/image1.png',
      'assets/reisty/image2.png',
      'assets/reisty/image3.png',
    ],
    baseColor: const Color(0xFFE91E63),
    technologies: ['Flutter', 'Firebase', 'Google Maps API', 'Node.js'],
    features: ['Real-time order tracking', 'Smart discovery', 'Social reviews'],
    role: 'Full Stack Flutter Developer',
  ),
  Project(
    title: 'Re:Chops',
    description: 'A restaurant reservation app with rich features.',
    logoPath: 'assets/chops/logo.png',
    splashPath: 'assets/chops/splash.png',
    screenshotPaths: [
      'assets/chops/image1.png',
      'assets/chops/image2.png',
      'assets/chops/image3.png',
    ],
    baseColor: const Color(0xFF4CAF50),
    technologies: ['Flutter', 'AWS', 'PostgreSQL', 'Redux'],
    features: ['Instant table booking', 'Curated menus', 'Loyalty rewards'],
    role: 'Mobile Architect',
  ),
  Project(
    title: 'Leisure Trove',
    description: 'A social app for travellers, tourists and locals.',
    logoPath: 'assets/leisure_trove/logo.png',
    splashPath: 'assets/leisure_trove/splash.png',
    screenshotPaths: [
      'assets/leisure_trove/image1.png',
      'assets/leisure_trove/image2.png',
      'assets/leisure_trove/image3.png',
    ],
    baseColor: const Color(0xFF2196F3),
    technologies: ['Flutter', 'Firebase Auth', 'Cloud Firestore', 'Stripe'],
    features: [
      'Local guides integration',
      'Itinerary planner',
      'Social moments',
    ],
    role: 'Lead Developer',
  ),
  Project(
    title: 'Errand Buddies',
    description: 'An e-commerce platform for goods and services.',
    logoPath: 'assets/errand_buddies/logo.png',
    splashPath: 'assets/errand_buddies/splash.png',
    screenshotPaths: [
      'assets/errand_buddies/image1.png',
      'assets/errand_buddies/image2.png',
      'assets/errand_buddies/image3.png',
    ],
    baseColor: const Color(0xFFFF9800),
    technologies: ['Flutter', 'MongoDB', 'Express', 'JWT'],
    features: [
      'Secure marketplace',
      'Peer-to-peer messaging',
      'Service bidding',
    ],
    role: 'Frontend Developer',
    isAiAccelerated: true,
  ),
  Project(
    title: 'Errand Vendors',
    description: 'Vendor app for order management and analysis.',
    logoPath: 'assets/errand_vendors/logo.png',
    splashPath: 'assets/errand_vendors/splash.png',
    screenshotPaths: [
      'assets/errand_vendors/image1.png',
      'assets/errand_vendors/image2.png',
      'assets/errand_vendors/image3.png',
    ],
    baseColor: const Color(0xFF9C27B0),
    technologies: ['Flutter', 'Chart.js integration', 'Firebase Messaging'],
    features: ['Advanced analytics', 'Inventory control', 'Order workflow'],
    role: 'Full Stack Engineer',
    isAiAccelerated: true,
  ),
  Project(
    title: 'Speed Reader',
    description: 'A PDF reader app with reading speed enhancements.',
    logoPath: 'assets/speed_reader/logo.png',
    splashPath: 'assets/speed_reader/splash.png',
    screenshotPaths: [
      'assets/speed_reader/image1.png',
      'assets/speed_reader/image2.png',
      'assets/speed_reader/image3.png',
    ],
    baseColor: const Color(0xFF607D8B),
    technologies: ['Flutter', 'PDF.js', 'Hive', 'Natural Language Processing'],
    features: ['Bionic reading mode', 'OCR support', 'Sync across devices'],
    role: 'Primary Developer',
    isAiAccelerated: true,
  ),
];
